{{/*
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.
*/}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gcm.fullname" . }}
  labels:
    {{- include "gcm.labels" . | nindent 4 }}
data:
  GCM_SINK: {{ .Values.monitoring.sink | quote }}
  GCM_CLUSTER: {{ .Values.monitoring.cluster | quote }}
  GCM_INTERVAL: {{ .Values.monitoring.interval | quote }}
