# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# Multi-stage Dockerfile combining Node Problem Detector (NPD) with GCM
# health checks. NPD runs as the entrypoint and invokes GCM health check
# binaries as custom plugin monitors.

FROM registry.k8s.io/node-problem-detector/node-problem-detector:v0.8.19 AS npd

ARG GCM_IMAGE=gcm:latest
FROM ${GCM_IMAGE}

COPY --from=npd /node-problem-detector /usr/local/bin/node-problem-detector

ENTRYPOINT ["/usr/local/bin/node-problem-detector"]
