apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-gcm-sentinel
  namespace: {{ .Release.Namespace }}
  labels:
    app: gcm-sentinel
    app.kubernetes.io/name: gcm-sentinel
    app.kubernetes.io/instance: {{ .Release.Name }}
